name: RSpec
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Ruby latest
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 'head'
        bundler-cache: true
    - name: Install dependencies
      run: bundle install
    - name: Run tests and collect coverage
      run: bundle exec rake
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
